### ISSUE TITLE
rename spring-cloud-starter-sentinel spring-cloud-starter-alibaba-sentinel

### ISSUE THREAD

**Issue by spencergibb** [spring-cloud-incubator/spring-cloud-alibabacloud#3]
The naming convention is 'spring-cloud-starter-<project>-<module>'. 
It looks like there is only one dependency, generally, if there would only be one dependency, there is no need for a starter. So another option would be to drop the starter and rename 'spring-cloud-alibaba-sentinel-autoconfigure' to 'spring-cloud-alibaba-sentinel'

**Comment by fangjian0423** [comment]
'spring-cloud-alibaba-sentinel-autoconfigure' has not been finished and we will consider is it need to separate two modules. Thanks!
